# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_project_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createProject(object):
    def setupUi(self, createProject):
        createProject.setObjectName("createProject")
        createProject.resize(630, 250)
        self.layoutWidget = QtWidgets.QWidget(createProject)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 611, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.projectName = QtWidgets.QLineEdit(self.layoutWidget)
        self.projectName.setObjectName("projectName")
        self.horizontalLayout_6.addWidget(self.projectName)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inputSpreadsheet = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputSpreadsheet.setObjectName("inputSpreadsheet")
        self.horizontalLayout.addWidget(self.inputSpreadsheet)
        self.inputSpreadsheetBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.inputSpreadsheetBtn.setObjectName("inputSpreadsheetBtn")
        self.horizontalLayout.addWidget(self.inputSpreadsheetBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.outputDir = QtWidgets.QLineEdit(self.layoutWidget)
        self.outputDir.setObjectName("outputDir")
        self.horizontalLayout_4.addWidget(self.outputDir)
        self.outputDirBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.outputDirBtn.setObjectName("outputDirBtn")
        self.horizontalLayout_4.addWidget(self.outputDirBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_8.addWidget(self.cancelButton)
        self.importBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.importBtn.setAutoDefault(False)
        self.importBtn.setDefault(True)
        self.importBtn.setObjectName("importBtn")
        self.horizontalLayout_8.addWidget(self.importBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_2)

        self.retranslateUi(createProject)
        QtCore.QMetaObject.connectSlotsByName(createProject)

    def retranslateUi(self, createProject):
        _translate = QtCore.QCoreApplication.translate
        createProject.setWindowTitle(_translate("createProject", "Dialog"))
        self.label_4.setText(_translate("createProject", "Project Name"))
        self.label.setText(_translate("createProject", "Input spreadsheet"))
        self.inputSpreadsheet.setText(_translate("createProject", "/path/to/spreadsheet"))
        self.inputSpreadsheetBtn.setText(_translate("createProject", "Browse"))
        self.label_2.setText(_translate("createProject", "Output directory"))
        self.outputDir.setText(_translate("createProject", "/path/to/output/directory"))
        self.outputDirBtn.setText(_translate("createProject", "Browse"))
        self.cancelButton.setText(_translate("createProject", "Cancel"))
        self.importBtn.setText(_translate("createProject", "Create"))
